PHONY : test
PHONY : testWatch
PHONY : testAll

test:
	stack test --test-arguments="--skip goldBachList'"

testWatch:
	stack test --file-watch --test-arguments="--skip goldBachList'"

testAll:
	stack test