name:           NNProblems
version:        0.1.0.0
homepage:       https://github.com/tooppoo/99_problems
author:         philomagi
maintainer:     philomagi<tooppoo56@gmail.com>
copyright:      2021 philomagi

library:
  source-dirs: src

dependencies:
  - base >= 4.7 && < 5

tests:
  NNProblems-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NNProblems
    - hspec
    - hspec-discover
    - QuickCheck
